/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JFrame;

/**
 *
 * @author Karan
 */
public class Home extends javax.swing.JFrame {
       GridBagLayout layout= new GridBagLayout();
       panel_dashboard dashboard;
       panel_company company;
       panel_manifest manifest;
       panel_shipment shipment;
       panel_product product;
       panel_werehouse werehouse;
       
       
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        dashboard=new panel_dashboard();
        company =new panel_company();
        manifest=new panel_manifest();
        shipment =new panel_shipment();
        product=new panel_product();
        werehouse=new panel_werehouse();
      
        panel_continer.setLayout(layout);
        GridBagConstraints c= new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        panel_continer.add(dashboard,c);
        c.gridx=0;
        c.gridy=0;
        panel_continer.add(company,c);
        c.gridx=0;
        c.gridy=0;
        panel_continer.add(manifest,c);
        c.gridx=0;
        c.gridy=0;
        panel_continer.add(shipment,c);
        c.gridx=0;
        c.gridy=0;
        panel_continer.add(product,c);
        c.gridx=0;
        c.gridy=0;
        panel_continer.add(werehouse,c);
        
        
        dashboard.setVisible(true);
        company.setVisible(false);
        manifest.setVisible(false);
        shipment.setVisible(false);
        product.setVisible(false);
        werehouse.setVisible(false);
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_exit = new javax.swing.JLabel();
        jLabel_mini = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_company = new javax.swing.JButton();
        btn_manifest = new javax.swing.JButton();
        btn_shipment = new javax.swing.JButton();
        btn_Dashboard = new javax.swing.JButton();
        panel_continer = new javax.swing.JPanel();
        btn_product = new javax.swing.JButton();
        btn_werehouse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jLabel5.setFont(new java.awt.Font("Imprint MT Shadow", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Staff In Boxes");

        jLabel_exit.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel_exit.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_exit.setText("x");
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
        });

        jLabel_mini.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabel_mini.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_mini.setText("-");
        jLabel_mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_miniMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(442, 442, 442)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_mini, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_mini, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_company.setBackground(new java.awt.Color(0, 51, 204));
        btn_company.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        btn_company.setForeground(new java.awt.Color(255, 255, 255));
        btn_company.setText("Company");
        btn_company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_companyActionPerformed(evt);
            }
        });

        btn_manifest.setBackground(new java.awt.Color(0, 51, 204));
        btn_manifest.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        btn_manifest.setForeground(new java.awt.Color(255, 255, 255));
        btn_manifest.setText("Manifest");
        btn_manifest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manifestActionPerformed(evt);
            }
        });

        btn_shipment.setBackground(new java.awt.Color(0, 51, 204));
        btn_shipment.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        btn_shipment.setForeground(new java.awt.Color(255, 255, 255));
        btn_shipment.setText("Shipment");
        btn_shipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_shipmentActionPerformed(evt);
            }
        });

        btn_Dashboard.setBackground(new java.awt.Color(0, 51, 204));
        btn_Dashboard.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        btn_Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        btn_Dashboard.setText("Dashboard");
        btn_Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_continerLayout = new javax.swing.GroupLayout(panel_continer);
        panel_continer.setLayout(panel_continerLayout);
        panel_continerLayout.setHorizontalGroup(
            panel_continerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        panel_continerLayout.setVerticalGroup(
            panel_continerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        btn_product.setBackground(new java.awt.Color(0, 51, 204));
        btn_product.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        btn_product.setForeground(new java.awt.Color(255, 255, 255));
        btn_product.setText("Product");
        btn_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productActionPerformed(evt);
            }
        });

        btn_werehouse.setBackground(new java.awt.Color(0, 51, 204));
        btn_werehouse.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        btn_werehouse.setForeground(new java.awt.Color(255, 255, 255));
        btn_werehouse.setText("Werehouse");
        btn_werehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_werehouseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_company, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_manifest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_product, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_shipment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_werehouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panel_continer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btn_Dashboard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_company)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_manifest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_product)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_shipment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_werehouse))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(panel_continer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_miniMouseClicked
        // TODO add your handling code here:

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_miniMouseClicked

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_exitMouseClicked

    private void btn_companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_companyActionPerformed
        dashboard.setVisible(false);
        company.setVisible(true);
        manifest.setVisible(false);
        shipment.setVisible(false);
        product.setVisible(false);
        werehouse.setVisible(false);
       
       
       
    }//GEN-LAST:event_btn_companyActionPerformed

    private void btn_DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DashboardActionPerformed
        dashboard.setVisible(true);
        company.setVisible(false);
        manifest.setVisible(false);
        shipment.setVisible(false);
        product.setVisible(false);
        werehouse.setVisible(false);
      
    }//GEN-LAST:event_btn_DashboardActionPerformed

    private void btn_manifestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manifestActionPerformed
        dashboard.setVisible(false);
        company.setVisible(false);
        manifest.setVisible(true);
        shipment.setVisible(false);
        product.setVisible(false);
        werehouse.setVisible(false);
      
    }//GEN-LAST:event_btn_manifestActionPerformed

    private void btn_shipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_shipmentActionPerformed
        dashboard.setVisible(false);
        company.setVisible(false);
        manifest.setVisible(false);
        shipment.setVisible(true);
        product.setVisible(false);
        werehouse.setVisible(false);
      
    }//GEN-LAST:event_btn_shipmentActionPerformed

    private void btn_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productActionPerformed
        dashboard.setVisible(false);
        company.setVisible(false);
        manifest.setVisible(false);
        shipment.setVisible(false);
        product.setVisible(true);
        werehouse.setVisible(false);
        
    }//GEN-LAST:event_btn_productActionPerformed

    private void btn_werehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_werehouseActionPerformed
        dashboard.setVisible(false);
        company.setVisible(false);
        manifest.setVisible(false);
        shipment.setVisible(false);
        product.setVisible(false);
        werehouse.setVisible(true);
       
    }//GEN-LAST:event_btn_werehouseActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Dashboard;
    private javax.swing.JButton btn_company;
    private javax.swing.JButton btn_manifest;
    private javax.swing.JButton btn_product;
    private javax.swing.JButton btn_shipment;
    private javax.swing.JButton btn_werehouse;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JLabel jLabel_mini;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel_continer;
    // End of variables declaration//GEN-END:variables
}
