/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Conteroller.CompanyController;
import Conteroller.ManifestController;
import Conteroller.ProductController;
import Conteroller.ShipmentController;
import Model.Manifest;
import Model.Product;
import Model.Shipment;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Karan
 */
public class panel_shipment extends javax.swing.JPanel {
    private int proid;
    private String date;
    public panel_shipment() {
        initComponents();
       date =new SimpleDateFormat("YYYY/MM/dd").format(Calendar.getInstance().getTime()) ;  
       txt_time.setText(date);
       ProductName();
    }
    public void ProductName(){
     ProductController contro= new ProductController();
        ResultSet rs= contro.DeliveryDetial();
        try {
             while (rs.next()) {
               String id = rs.getString("pid");
                jComboBox_id.addItem(id);
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(panel_company.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_destination = new javax.swing.JComboBox<>();
        txt_time = new javax.swing.JTextField();
        jLabel_time = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_internalCost = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        label_CustomerCost = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_internalCost = new javax.swing.JLabel();
        btn_customercost = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_weight = new javax.swing.JTextField();
        jComboBox_id = new javax.swing.JComboBox<>();
        txt_pname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_refresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jLabel5.setFont(new java.awt.Font("Imprint MT Shadow", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Shipment");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jComboBox_destination.setBackground(new java.awt.Color(0, 51, 204));
        jComboBox_destination.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jComboBox_destination.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kathmandu", "Ilam", "Lalitpur", "Bhaktbur", "Pokhera", "Biratnagar", "Bharatpur", "Birganj", "Butwal", "Dharan", "Dhangadhi", "Janakpur", "Hetauda", "Itahari", "Napalganj", "Gorkha", " " }));
        jComboBox_destination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_destinationActionPerformed(evt);
            }
        });

        txt_time.setBackground(new java.awt.Color(0, 51, 204));
        txt_time.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txt_time.setForeground(new java.awt.Color(255, 255, 255));
        txt_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timeActionPerformed(evt);
            }
        });

        jLabel_time.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jLabel_time.setForeground(new java.awt.Color(0, 51, 204));
        jLabel_time.setText("Today Date:");

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Product Name: ");

        jLabel2.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Product Destination:");

        txt_quantity.setBackground(new java.awt.Color(0, 51, 204));
        txt_quantity.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Product Quantity:");

        btn_add.setBackground(new java.awt.Color(0, 51, 204));
        btn_add.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("Create Shipment");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_internalCost.setBackground(new java.awt.Color(0, 51, 204));
        btn_internalCost.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        btn_internalCost.setForeground(new java.awt.Color(255, 255, 255));
        btn_internalCost.setText("Calculate");
        btn_internalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_internalCostActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("Cost To Customer:");

        label_CustomerCost.setBackground(new java.awt.Color(0, 51, 204));
        label_CustomerCost.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        label_CustomerCost.setForeground(new java.awt.Color(0, 51, 204));
        label_CustomerCost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setText("Internal Cost");

        label_internalCost.setBackground(new java.awt.Color(0, 51, 204));
        label_internalCost.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        label_internalCost.setForeground(new java.awt.Color(0, 51, 204));
        label_internalCost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_customercost.setBackground(new java.awt.Color(0, 51, 204));
        btn_customercost.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        btn_customercost.setForeground(new java.awt.Color(255, 255, 255));
        btn_customercost.setText("Calculate ");
        btn_customercost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customercostActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Product Weight:");

        txt_weight.setBackground(new java.awt.Color(0, 51, 204));
        txt_weight.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        txt_weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_weightActionPerformed(evt);
            }
        });

        jComboBox_id.setBackground(new java.awt.Color(0, 51, 204));
        jComboBox_id.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jComboBox_id.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search By Product ID" }));
        jComboBox_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_idActionPerformed(evt);
            }
        });

        txt_pname.setBackground(new java.awt.Color(0, 51, 204));
        txt_pname.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setText("Product  ID: ");

        jLabel9.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setText("To Create Shipment You have to Calculate Internal Cost and Customer cost ");

        btn_refresh.setBackground(new java.awt.Color(0, 51, 204));
        btn_refresh.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        btn_refresh.setForeground(new java.awt.Color(255, 255, 255));
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel_time)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_time, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_quantity, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_pname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox_id, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_weight))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_destination, 0, 153, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(label_CustomerCost, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(label_internalCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_customercost, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_internalCost)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(252, 252, 252)
                                .addComponent(btn_add)
                                .addGap(26, 26, 26)
                                .addComponent(btn_refresh)))))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_time)
                    .addComponent(txt_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_id, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(label_internalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_internalCost))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7))
                            .addComponent(label_CustomerCost, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_customercost)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_refresh))
                .addGap(89, 89, 89))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timeActionPerformed

    private void jComboBox_destinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_destinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_destinationActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
       
            if (txt_pname.getText().isEmpty()||txt_quantity.getText().isEmpty()||txt_weight.getText().isEmpty()) {
             JOptionPane.showMessageDialog(null, "Please fill all text field or click on Search By Product ID ");
        }else if(label_CustomerCost.getText().isEmpty()||label_internalCost.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Calculate Internal cost and Customer Cost ");
        }else{
                
                float internalCost= Float.parseFloat(label_internalCost.getText());
                float customerCost= Float.parseFloat(label_CustomerCost.getText());
                Shipment ss=new Shipment();
                ss.setInternalcost(internalCost);
                ss.setCustomerCost(customerCost);
                ss.setPid(proid);
                     ShipmentController scc= new ShipmentController();
                       int res=  scc.InsertShipment(ss);
                        if (res > 0) {
                            JOptionPane.showMessageDialog(null, "Shipment Created Sucessfully");
                           
                            txt_pname.setText(null);
                            txt_quantity.setText(null);
                            txt_weight.setText(null);
                            label_CustomerCost.setText(null);
                            label_internalCost.setText(null);
                            

                        } else {
                            JOptionPane.showMessageDialog(null, "Shipment Cannot Created");

                        }
                        
                        Product p= new Product();
                           p.setPid(proid);
                           ProductController pc= new ProductController();
                          int re= pc.UpdateDeliver(p);
                          jComboBox_id.removeAllItems();
                          ProductName();
                          
            
            }
            
               
        
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_internalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_internalCostActionPerformed
        String destination=(String) jComboBox_destination.getSelectedItem();
        int  quantity=Integer.parseInt(txt_quantity.getText());
        int weight=Integer.parseInt(txt_weight.getText());
        ShipmentController scc= new ShipmentController();
        ResultSet res=scc.SearchCost(destination);
        int locationCost=0;
        try {
            while(res.next()){
                locationCost=res.getInt("price");
            }
        } catch (SQLException ex) {
            Logger.getLogger(panel_shipment.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        int internalcost= locationCost+(weight*10);
        String total = String.valueOf(internalcost);
        
       label_internalCost.setText(total);
        
    }//GEN-LAST:event_btn_internalCostActionPerformed

    private void btn_customercostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customercostActionPerformed
       String destination=(String) jComboBox_destination.getSelectedItem();
        int  quantity=Integer.parseInt(txt_quantity.getText());
        int weight=Integer.parseInt(txt_weight.getText());
        ShipmentController scc= new ShipmentController();
        ResultSet res=scc.SearchCost(destination);
        int locationCost=0;
        try {
            while(res.next()){
                locationCost=res.getInt("price");
            }
        } catch (SQLException ex) {
            Logger.getLogger(panel_shipment.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        int internalcost= locationCost+(weight*10);
        float costForCustomer=internalcost+((internalcost*20)/100);
        String total = String.valueOf(costForCustomer);
        
       label_CustomerCost.setText(total);
    }//GEN-LAST:event_btn_customercostActionPerformed

    private void jComboBox_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_idActionPerformed
      
        if (jComboBox_id.getSelectedItem()!=null) {
             if (jComboBox_id.getSelectedItem().equals("Search By Product ID")) {
             JOptionPane.showMessageDialog(null, "Please Select Product Id");
        } else {
        proid = Integer.valueOf((String) this.jComboBox_id.getSelectedItem());
        Product p=new Product();
        p.setPid(proid);
        ProductController contro= new ProductController();
        ResultSet rs= contro.getProductName(p);
        try {
            while (rs.next()) {
                int quantity= rs.getInt("quantity");
                String quant=Integer.toString(quantity);
                String destination=rs.getString("destination");
                txt_quantity.setText(quant);
                jComboBox_destination.setSelectedItem(destination);
                int weight= rs.getInt("weight");
                String weightt=Integer.toString(weight);
                txt_weight.setText(weightt);
                String pname=rs.getString("name");
                txt_pname.setText(pname);

            }
        } catch (SQLException ex) {
            Logger.getLogger(panel_company.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        }
        
        
    }//GEN-LAST:event_jComboBox_idActionPerformed

    private void txt_weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_weightActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        jComboBox_id.removeAllItems();
        ProductName();
    }//GEN-LAST:event_btn_refreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_customercost;
    private javax.swing.JButton btn_internalCost;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JComboBox<String> jComboBox_destination;
    private javax.swing.JComboBox<String> jComboBox_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_time;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_CustomerCost;
    private javax.swing.JLabel label_internalCost;
    private javax.swing.JTextField txt_pname;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_time;
    private javax.swing.JTextField txt_weight;
    // End of variables declaration//GEN-END:variables
}
